name: "Frank Silvera Writer's Workshop-work site"
favicon: null
layout_spectrum: 0.9311091189738363
typography_spectrum: 0.39435164420865476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.09680731338448822
  lightness: 0.6199388480745256
  saturation: 0.5825176523067057
  rhythmicContrast: 0.9369563546497375
purpose: []
